### ISSUE TITLE
jKind Starting Script (on a Mac)

### ISSUE THREAD

**Issue by AFifarek** [agacek/jkind#28]
Platform: **Mac OS 10.11.3**

I know you guys aren't officially supporting Mac but I wanted to let you know that we were having a problem in-house running the following script:
#!/bin/sh
JKIND_PATH=$(readlink -e $0)
JKIND_DIR=$(dirname $JKIND_PATH)
java -jar $JKIND_DIR/jkind.jar -jkind "$@"

The command line in the terminal provides an illegal usage on readlink -f

On the Mac systems here, we are working around this issue by using the old starting script:
#!/bin/sh
java -jar $(dirname $0)/jkind.jar -jkind "$@"

**Comment by agacek** [comment]
The new version of the script comes from David Greve. On Linux, it allows you to link to the JKind script from a common bin directory while still allowing the script to know where the JKind home directory is. I'll have to find a way to merge the two scripts. Unfortunately, I don't have access to a Mac right now.

**Comment by AFifarek** [comment]
Over here we have access to a few Macs (not my system)

I did find a stackoverflow link that we may try here. It looks a few years old but might be a starting point.
[http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac](url)

**Comment by agacek** [comment]
David Greve has furnished a new version of the script that should work on OS X. Please test this out and let me know:

  https://github.com/agacek/jkind/blob/master/scripts/jkind

**Comment by jonimp9** [comment]
Yes, that script works on my Mac. Thanks.
