### ISSUE TITLE
Non-constant division

### ISSUE THREAD

**Issue by lememta** [agacek/jkind#30]
The non-constant division is a bit restrictive. Is there a way to by-pass this? Maybe via an option.

`jkind --xml_to_stdout -main AltitudeControl_Demo_SAFETY_REQUIREMENT_1 AltitudeControl_Demo.lus`

[AltitudeControl_Demo.lus.zip](https://github.com/agacek/jkind/files/319570/AltitudeControl_Demo.lus.zip)

**Comment by agacek** [comment]
If you use '-solver z3' the non-constant division error becomes just a warning. Z3 is the only solver with non-linear support that JKind uses.

**Comment by lememta** [comment]
OK Thanks. Btw, is it possible when `--xml_to_stdout` is specified not output non xml infos, e.g. 'Warning at line 136:74 non-constant division'. It makes the parsing a bit 'dirty'.

**Comment by agacek** [comment]
I took a look and it would be rather annoying to redirect the warnings and errors in that case. Sorry.
