### ISSUE TITLE
Z3-related crash regarding parsing Solver output

### ISSUE THREAD

**Issue by lgwagner** [agacek/jkind#45]
JKind is crashing on the provided example model (you will have to unzip error.zip and run error.lus to reproduce the error.

jkind -solver z3 -smooth -no_slicing error.lus

This produces the following error:

![image](https://user-images.githubusercontent.com/2699181/41878859-8c5efdc2-789c-11e8-8234-ee9855fb5d2e.png)

This is using JKind version 4.0.1 and Z3 4.7.1.  The error was reproduced on JKind 4.0.1 and Z3 4.6.0 and 4.6.2.

[error.zip](https://github.com/agacek/jkind/files/2134915/error.zip)

**Comment by agacek** [comment]
Thanks!
