### ISSUE TITLE
Arithmetic Exception

### ISSUE THREAD

**Issue by lgwagner** [agacek/jkind#47]
Attached model exercises an arithmetic exception.

Solver = Z3 (4.7.1)
JKind (latest commit from master, em in an Eclipse tool)

[error.txt](https://github.com/agacek/jkind/files/2384835/error.txt)
![error_image](https://user-images.githubusercontent.com/2699181/45574557-07003900-b836-11e8-9109-1ca344e09b4e.png)

**Comment by lgwagner** [comment]
Hmmm...nevermind. I believe we discussed this quite some time ago. I think back then you told me there was nothing to consider.

**Comment by agacek** [comment]
Yes, nonlinear is a bit of a pain. In particular, if you divide by zero,
the SMT solver treats the result as arbitrary. That means we are not able
to simulate any counterexamples with division by zero. I think the best
workaround is to ensure that the variables you divide by are never zero
(either through assertion or other means that are sound for your problem).

That said, JKind should produce a better message in this case.
